### ISSUE TITLE
Hvordan bør Data carrier identifier skille mellom NTIN og GTIN type produktkode?

### ISSUE THREAD

**Issue by stinejohans1** [HL7Norway/SAFEST#1]
Produktkodene som mottas fra farmalogg definerer en produktkodestandard, denne kan være NTIN eller GTIN. 

På Identifier på pakning (MedicinalProductPackaged), bør man lage èn slice for hver type, med "fixed value" i system, altså: 
dataCarrierIdentifierNTIN (system: https://farmalogg.no/produktkode/NTIN)
dataCarrierIdentifierGTIN (system: https://farmalogg.no/produktkode/GTIN)

Eller: 
Lage èn slice, hvor system ikke er fixed value, og man legger riktig system inn, avhengig av typen produktkodestandard?

**Comment by stinejohans1** [comment]
@rockphotog kjente du noen som kanskje har noe input om temaet over? Eller ble vi egentlig enige om at det er mer brukervennlig med to slices som hadde hvert sitt navn (dataCarrierIdentifierNTIN  og  dataCarrierIdentifierGTIN).

**Comment by rockphotog** [comment]
Hei @HL7Norway/tsk @HL7Norway/utviklere-basisprofiler alle! Nå har SVL gått i gang med SAFEST-profilering, så fint hvis dere kan følge med i diskusjoner/issues her. Jeg vil tagge enkelte av dere på aktuelle problemstillinger som kommer opp. 

@thomiz @kennethmyhra @oaassv

**Comment by oaassv** [comment]
Skal vi sette opp et møte med TSK for en gjennomgang av arbeidet så langt?

**Comment by stinejohans1** [comment]
Ja, gjerne det.

**Comment by oaassv** [comment]
Den er god. Foreslår 1,5 timer. Kan du foreslå noen tidspunkt som passer for dere første uka etter påske?

**Comment by stinejohans1** [comment]
Forslag til tid:
Onsdag 15 april; 9-12 eller 13-16
Torsdag 16 april: 13-16
Fredag 17 apri: 9-13

**Comment by oaassv** [comment]
Flott, kan du sende meg din e-mail. Har dere kommet så langt at dere har profiler publisert på Simplifier eller annet materiell som kan sendes ut i forkant?

øyvind     På mandag 30. mars 2020, 07:41:37 CEST skrev Stine Johansen <notifications@github.com> følgende:  
 
 


Forslag til tid:
Onsdag 15 april; 9-12 eller 13-16
Torsdag 16 april: 13-16
Fredag 17 apri: 9-13

**Comment by stinejohans1** [comment]
Alt som er laget ligger publisert på simplifier: https://simplifier.net/safest og ligger i kildekoden her, i en egen branch enn så lenge. 

epost:
stine.johansen at soprasteria.com

**Comment by stinejohans1** [comment]
Opprinnelig spørsmål her var ang. NTIN og GTIN, dette kommer ikke SAFEST til å levere per nå, så jeg lukker denne.
