### ISSUE TITLE
National profile for submitting adverse event 

### ISSUE THREAD

**Issue by losolio** [HL7Norway/SAFEST#4]
There is interest from the regional health trusts to submit reports of adverse events from medical drugs, as well as  the usage of vaccines. I am not sure if nutrimental supplements should be included as well. 

The national portal [Melde.no](https://melde.no) is established for submitting reports on medical errors and adverse outcomes. We are now looking into expanding this with an open API, with the intention of enabling system to system communication of adverse events from E*R source systems and/or electronic quality systems. 

Our guess is that the resource [AdverseEvent](https://www.hl7.org/fhir/adverseevent.html) could be of interest. 

Where could we find more information on the way forward for investigating this track?

**Comment by thomiz** [comment]
This is an interesting question. I guess the case here is the events from medical  substances and that is a case that is covereed in the AllergyIntolerance resource. One project that is working on profiling this resource for use is Kjernejournal. There is no implementation guide yet, but the profiles are available here: 
https://simplifier.net/kjernejournalr4

Maybe Vidar Mehti or Andreas Owe can give some insight, can not find them on Github, but they are active in the SIMPLIFIER project.

**Comment by oaassv** [comment]
Lukker denne - er svart ut.
